// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZsayCO6uW4SNCwrhxxjJ_uDwYLm9HwY',
    appId: '1:960784435283:web:3a5b51ac10e09017b35ea6',
    messagingSenderId: '960784435283',
    projectId: 'edge-fx',
    authDomain: 'edge-fx.firebaseapp.com',
    storageBucket: 'edge-fx.firebasestorage.app',
    measurementId: 'G-XXMPH08NR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyZRE4G3-SlMduFsiFp-w70j4UdwRPzA',
    appId: '1:960784435283:android:691bf127e5a0c7feb35ea6',
    messagingSenderId: '960784435283',
    projectId: 'edge-fx',
    storageBucket: 'edge-fx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSODUJ02-fKLwZFYpcE_7zpZi2txXEzTs',
    appId: '1:960784435283:ios:311e3341dd1791fab35ea6',
    messagingSenderId: '960784435283',
    projectId: 'edge-fx',
    storageBucket: 'edge-fx.firebasestorage.app',
    iosBundleId: 'com.example.edgeFx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSODUJ02-fKLwZFYpcE_7zpZi2txXEzTs',
    appId: '1:960784435283:ios:311e3341dd1791fab35ea6',
    messagingSenderId: '960784435283',
    projectId: 'edge-fx',
    storageBucket: 'edge-fx.firebasestorage.app',
    iosBundleId: 'com.example.edgeFx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ZsayCO6uW4SNCwrhxxjJ_uDwYLm9HwY',
    appId: '1:960784435283:web:4bef37dbe7ee15dcb35ea6',
    messagingSenderId: '960784435283',
    projectId: 'edge-fx',
    authDomain: 'edge-fx.firebaseapp.com',
    storageBucket: 'edge-fx.firebasestorage.app',
    measurementId: 'G-17N64VRRVR',
  );
}
